services:
  backend:
    container_name: backend
    build:
      context: ./backend/PantioAPI
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_HOST_PORT}:8080"
    networks:
      - PantioNetwork
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}
      start_period: ${HEALTHCHECK_START_PERIOD}

  frontend:
    container_name: frontend
    build:
      context: ./frontend/PantioApp
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_HOST_PORT}:80"
    networks:
      - PantioNetwork
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}
      start_period: ${HEALTHCHECK_START_PERIOD}

networks:
  PantioNetwork:
    driver: bridge
