// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PantioRepository.EntityFramework;

#nullable disable

namespace PantioRepository.EntityFramework.EFMigrations
{
    [DbContext(typeof(PantioDbContext))]
    [Migration("20260511121636_AddInactiveUserTracking")]
    partial class AddInactiveUserTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PantioClassLibrary.Entities.ExpiryDate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("CategoryDefaultUsedDays")
                        .HasColumnType("integer")
                        .HasColumnName("category_default_used_days");

                    b.Property<DateOnly>("EstimatedExpiry")
                        .HasColumnType("date")
                        .HasColumnName("estimated_expiry");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_item_id");

                    b.Property<bool>("IsManualOverride")
                        .HasColumnType("boolean")
                        .HasColumnName("is_manual_override");

                    b.Property<DateTime?>("NotificationSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("notification_sent_at");

                    b.Property<DateOnly?>("OverrideDate")
                        .HasColumnType("date")
                        .HasColumnName("override_date");

                    b.HasKey("Id");

                    b.HasIndex("EstimatedExpiry");

                    b.HasIndex("InventoryItemId")
                        .IsUnique();

                    b.ToTable("expiry_dates");
                });

            modelBuilder.Entity("PantioClassLibrary.Entities.ExpiryNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Acknowledged")
                        .HasColumnType("boolean")
                        .HasColumnName("acknowledged");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<int>("DaysBeforeExpiry")
                        .HasColumnType("integer")
                        .HasColumnName("days_before_expiry");

                    b.Property<Guid>("ExpiryDateId")
                        .HasColumnType("uuid")
                        .HasColumnName("expiry_date_id");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiryDateId");

                    b.HasIndex("UserId");

                    b.ToTable("expiry_notifications");
                });

            modelBuilder.Entity("PantioClassLibrary.Entities.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("inventories");
                });

            modelBuilder.Entity("PantioClassLibrary.Entities.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<string>("AddedVia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("added_via");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("Ean")
                        .HasColumnType("text")
                        .HasColumnName("ean");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_id");

                    b.Property<string>("OffTag")
                        .HasColumnType("text")
                        .HasColumnName("off_tag");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_name");

                    b.Property<float>("Quantity")
                        .HasColumnType("real")
                        .HasColumnName("quantity");

                    b.Property<string>("QuantityUnit")
                        .HasColumnType("text")
                        .HasColumnName("quantity_unit");

                    b.Property<Guid?>("ReceiptLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_line_id");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("StorageLocation")
                        .HasColumnType("text")
                        .HasColumnName("storage_location");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Ean");

                    b.HasIndex("ReceiptLineId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("InventoryId", "Status");

                    b.ToTable("inventory_items");
                });

            modelBuilder.Entity("PantioClassLibrary.Entities.NutritionFacts", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cached_at");

                    b.Property<float?>("Carbohydrates100g")
                        .HasColumnType("real")
                        .HasColumnName("carbohydrates_100g");

                    b.Property<float?>("EnergyKcal100g")
                        .HasColumnType("real")
                        .HasColumnName("energy_kcal_100g");

                    b.Property<float?>("Fat100g")
                        .HasColumnType("real")
                        .HasColumnName("fat_100g");

                    b.Property<Guid?>("InventoryItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_item_id");

                    b.Property<string>("NutritionDataPer")
                        .HasColumnType("text")
                        .HasColumnName("nutrition_data_per");

                    b.Property<Guid?>("ProductCacheId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_cache_id");

                    b.Property<float?>("Proteins100g")
                        .HasColumnType("real")
                        .HasColumnName("proteins_100g");

                    b.Property<float?>("Salt100g")
                        .HasColumnType("real")
                        .HasColumnName("salt_100g");

                    b.Property<float?>("SaturatedFat100g")
                        .HasColumnType("real")
                        .HasColumnName("saturated_fat_100g");

                    b.Property<float?>("Sugars100g")
                        .HasColumnType("real")
                        .HasColumnName("sugars_100g");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId")
                        .IsUnique();

                    b.HasIndex("ProductCacheId")
                        .IsUnique();

                    b.ToTable("nutrition_facts");
                });

            modelBuilder.Entity("PantioClassLibrary.Entities.ProductCache", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cached_at");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("Ean")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ean");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_name");

                    b.Property<string>("Quantity")
                        .HasColumnType("text")
                        .HasColumnName("quantity");

                    b.Property<string>("QuantityUnit")
                        .HasColumnType("text")
                        .HasColumnName("quantity_unit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId", "Ean")
                        .IsUnique();

                    b.ToTable("product_cache");
                });

            modelBuilder.Entity("PantioClassLibrary.Entities.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DefaultShelfLifeDays")
                        .HasColumnType("integer")
                        .HasColumnName("default_shelf_life_days");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("OffTag")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("off_tag");

                    b.HasKey("Id");

                    b.ToTable("product_categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DefaultShelfLifeDays = 4,
                            DisplayName = "Fersk kød",
                            OffTag = "en:fresh-meats"
                        },
                        new
                        {
                            Id = 2,
                            DefaultShelfLifeDays = 2,
                            DisplayName = "Fersk fisk",
                            OffTag = "en:fresh-fish"
                        },
                        new
                        {
                            Id = 3,
                            DefaultShelfLifeDays = 7,
                            DisplayName = "Mælk",
                            OffTag = "en:milks"
                        },
                        new
                        {
                            Id = 4,
                            DefaultShelfLifeDays = 14,
                            DisplayName = "Yoghurt",
                            OffTag = "en:yogurts"
                        },
                        new
                        {
                            Id = 5,
                            DefaultShelfLifeDays = 21,
                            DisplayName = "Ost",
                            OffTag = "en:cheeses"
                        },
                        new
                        {
                            Id = 6,
                            DefaultShelfLifeDays = 28,
                            DisplayName = "Æg",
                            OffTag = "en:eggs"
                        },
                        new
                        {
                            Id = 7,
                            DefaultShelfLifeDays = 7,
                            DisplayName = "Mejeriprodukter",
                            OffTag = "en:dairy"
                        },
                        new
                        {
                            Id = 8,
                            DefaultShelfLifeDays = 5,
                            DisplayName = "Friske grøntsager",
                            OffTag = "en:fresh-vegetables"
                        },
                        new
                        {
                            Id = 9,
                            DefaultShelfLifeDays = 5,
                            DisplayName = "Frisk frugt",
                            OffTag = "en:fresh-fruits"
                        },
                        new
                        {
                            Id = 10,
                            DefaultShelfLifeDays = 3,
                            DisplayName = "Frisk brød",
                            OffTag = "en:fresh-bread"
                        },
                        new
                        {
                            Id = 11,
                            DefaultShelfLifeDays = 5,
                            DisplayName = "Pålæg",
                            OffTag = "en:cooked-meats"
                        },
                        new
                        {
                            Id = 12,
                            DefaultShelfLifeDays = 7,
                            DisplayName = "Brød",
                            OffTag = "en:bread"
                        },
                        new
                        {
                            Id = 13,
                            DefaultShelfLifeDays = 30,
                            DisplayName = "Drikkevarer",
                            OffTag = "en:beverages"
                        },
                        new
                        {
                            Id = 14,
                            DefaultShelfLifeDays = 7,
                            DisplayName = "Juice",
                            OffTag = "en:juices"
                        },
                        new
                        {
                            Id = 15,
                            DefaultShelfLifeDays = 180,
                            DisplayName = "Sovse og dressinger",
                            OffTag = "en:sauces"
                        },
                        new
                        {
                            Id = 16,
                            DefaultShelfLifeDays = 180,
                            DisplayName = "Krydderier",
                            OffTag = "en:condiments"
                        },
                        new
                        {
                            Id = 17,
                            DefaultShelfLifeDays = 90,
                            DisplayName = "Kiks og kager",
                            OffTag = "en:biscuits-and-cakes"
                        },
                        new
                        {
                            Id = 18,
                            DefaultShelfLifeDays = 180,
                            DisplayName = "Chokolade",
                            OffTag = "en:chocolate"
                        },
                        new
                        {
                            Id = 19,
                            DefaultShelfLifeDays = 180,
                            DisplayName = "Frosne fødevarer",
                            OffTag = "en:frozen-foods"
                        },
                        new
                        {
                            Id = 20,
                            DefaultShelfLifeDays = 730,
                            DisplayName = "Konservesvarer",
                            OffTag = "en:canned-foods"
                        },
                        new
                        {
                            Id = 21,
                            DefaultShelfLifeDays = 730,
                            DisplayName = "Pasta",
                            OffTag = "en:pasta"
                        },
                        new
                        {
                            Id = 22,
                            DefaultShelfLifeDays = 730,
                            DisplayName = "Ris",
                            OffTag = "en:rice"
                        },
                        new
                        {
                            Id = 23,
                            DefaultShelfLifeDays = 365,
                            DisplayName = "Morgenmadsprodukter",
                            OffTag = "en:cereals"
                        },
                        new
                        {
                            Id = 24,
                            DefaultShelfLifeDays = 365,
                            DisplayName = "Olie",
                            OffTag = "en:oils"
                        });
                });

            modelBuilder.Entity("PantioClassLibrary.Entities.Receipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DsgReceiptId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dsg_receipt_id");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at");

                    b.Property<float>("MemberDiscountDkk")
                        .HasColumnType("real")
                        .HasColumnName("member_discount_dkk");

                    b.Property<float>("OtherDiscountDkk")
                        .HasColumnType("real")
                        .HasColumnName("other_discount_dkk");

                    b.Property<string>("ReceiptType")
                        .HasColumnType("text")
                        .HasColumnName("receipt_type");

                    b.Property<float>("SalesTotalDkk")
                        .HasColumnType("real")
                        .HasColumnName("sales_total_dkk");

                    b.Property<Guid>("StoreConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_connection_id");

                    b.Property<string>("StoreName")
                        .HasColumnType("text")
                        .HasColumnName("store_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DsgReceiptId")
                        .IsUnique();

                    b.HasIndex("StoreConnectionId");

                    b.HasIndex("UserId");

                    b.ToTable("receipts");
                });

            modelBuilder.Entity("PantioClassLibrary.Entities.ReceiptLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArticleDescription")
                        .HasColumnType("text")
                        .HasColumnName("article_description");

                    b.Property<float>("DiscountDkk")
                        .HasColumnType("real")
                        .HasColumnName("discount_dkk");

                    b.Property<string>("Discounts")
                        .HasColumnType("jsonb")
                        .HasColumnName("discounts");

                    b.Property<string>("Ean")
                        .HasColumnType("text")
                        .HasColumnName("ean");

                    b.Property<string>("ItemType")
                        .HasColumnType("text")
                        .HasColumnName("item_type");

                    b.Property<float>("NormalPriceDkk")
                        .HasColumnType("real")
                        .HasColumnName("normal_price_dkk");

                    b.Property<bool>("ProcessedToInventory")
                        .HasColumnType("boolean")
                        .HasColumnName("processed_to_inventory");

                    b.Property<float>("QtyInSalesUnit")
                        .HasColumnType("real")
                        .HasColumnName("qty_in_sales_unit");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_id");

                    b.Property<float>("SalesPriceDkk")
                        .HasColumnType("real")
                        .HasColumnName("sales_price_dkk");

                    b.Property<float>("TaxAmountDkk")
                        .HasColumnType("real")
                        .HasColumnName("tax_amount_dkk");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptId");

                    b.ToTable("receipt_lines");
                });

            modelBuilder.Entity("PantioClassLibrary.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Instructions")
                        .HasColumnType("text")
                        .HasColumnName("instructions");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<float>("Portions")
                        .HasColumnType("real")
                        .HasColumnName("portions");

                    b.Property<Guid?>("SuggestionBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("suggestion_batch_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("recipes");
                });

            modelBuilder.Entity("PantioClassLibrary.Entities.RecipeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("InventoryItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_item_id");

                    b.Property<string>("MeasuringUnit")
                        .HasColumnType("text")
                        .HasColumnName("measuring_unit");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_name");

                    b.Property<float>("Quantity")
                        .HasColumnType("real")
                        .HasColumnName("quantity");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId")
                        .HasFilter("inventory_item_id IS NULL");

                    b.HasIndex("RecipeId");

                    b.ToTable("recipe_entries");
                });

            modelBuilder.Entity("PantioClassLibrary.Entities.ShoppingList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("shopping_lists");
                });

            modelBuilder.Entity("PantioClassLibrary.Entities.ShoppingListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_checked");

                    b.Property<string>("MeasuringUnit")
                        .HasColumnType("text")
                        .HasColumnName("measuring_unit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<float?>("Quantity")
                        .HasColumnType("real")
                        .HasColumnName("quantity");

                    b.Property<Guid>("ShoppingListId")
                        .HasColumnType("uuid")
                        .HasColumnName("shopping_list_id");

                    b.HasKey("Id");

                    b.HasIndex("ShoppingListId", "IsChecked");

                    b.ToTable("shopping_list_items");
                });

            modelBuilder.Entity("PantioClassLibrary.Entities.StoreConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessToken")
                        .HasColumnType("text")
                        .HasColumnName("access_token");

                    b.Property<string>("Chain")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("chain");

                    b.Property<DateTime>("ConnectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("connected_at");

                    b.Property<DateTime?>("DisconnectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disconnected_at");

                    b.Property<string>("GigyaSessionToken")
                        .HasColumnType("text")
                        .HasColumnName("gigya_session_token");

                    b.Property<string>("IdToken")
                        .HasColumnType("text")
                        .HasColumnName("id_token");

                    b.Property<DateTime?>("LastPolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_polled_at");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("TokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("token_expires_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("LastPolledAt");

                    b.HasIndex("UserId", "Chain")
                        .IsUnique();

                    b.ToTable("store_connections");
                });

            modelBuilder.Entity("PantioClassLibrary.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Auth0Sub")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("auth0_sub");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletionWarningSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_warning_sent_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.Property<bool>("OnboardingDone")
                        .HasColumnType("boolean")
                        .HasColumnName("onboarding_done");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Auth0Sub")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("PantioClassLibrary.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<int?>("HouseholdSize")
                        .HasColumnType("integer")
                        .HasColumnName("household_size");

                    b.Property<string>("Locale")
                        .HasColumnType("text")
                        .HasColumnName("locale");

                    b.Property<string>("NotificationPrefs")
                        .HasColumnType("jsonb")
                        .HasColumnName("notification_prefs");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_profiles");
                });

            modelBuilder.Entity("PantioClassLibrary.Entities.ExpiryDate", b =>
                {
                    b.HasOne("PantioClassLibrary.Entities.InventoryItem", "InventoryItem")
                        .WithOne("ExpiryDate")
                        .HasForeignKey("PantioClassLibrary.Entities.ExpiryDate", "InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("PantioClassLibrary.Entities.ExpiryNotification", b =>
                {
                    b.HasOne("PantioClassLibrary.Entities.ExpiryDate", "ExpiryDate")
                        .WithMany("ExpiryNotifications")
                        .HasForeignKey("ExpiryDateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PantioClassLibrary.Entities.User", "User")
                        .WithMany("ExpiryNotifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpiryDate");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PantioClassLibrary.Entities.Inventory", b =>
                {
                    b.HasOne("PantioClassLibrary.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PantioClassLibrary.Entities.InventoryItem", b =>
                {
                    b.HasOne("PantioClassLibrary.Entities.ProductCategory", "Category")
                        .WithMany("InventoryItems")
                        .HasForeignKey("CategoryId");

                    b.HasOne("PantioClassLibrary.Entities.Inventory", "Inventory")
                        .WithMany("InventoryItems")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PantioClassLibrary.Entities.ReceiptLine", "ReceiptLine")
                        .WithOne("InventoryItem")
                        .HasForeignKey("PantioClassLibrary.Entities.InventoryItem", "ReceiptLineId");

                    b.HasOne("PantioClassLibrary.Entities.User", null)
                        .WithMany("InventoryItems")
                        .HasForeignKey("UserId");

                    b.Navigation("Category");

                    b.Navigation("Inventory");

                    b.Navigation("ReceiptLine");
                });

            modelBuilder.Entity("PantioClassLibrary.Entities.NutritionFacts", b =>
                {
                    b.HasOne("PantioClassLibrary.Entities.InventoryItem", "InventoryItem")
                        .WithOne("NutritionFacts")
                        .HasForeignKey("PantioClassLibrary.Entities.NutritionFacts", "InventoryItemId");

                    b.HasOne("PantioClassLibrary.Entities.ProductCache", "ProductCache")
                        .WithOne("NutritionFacts")
                        .HasForeignKey("PantioClassLibrary.Entities.NutritionFacts", "ProductCacheId");

                    b.Navigation("InventoryItem");

                    b.Navigation("ProductCache");
                });

            modelBuilder.Entity("PantioClassLibrary.Entities.ProductCache", b =>
                {
                    b.HasOne("PantioClassLibrary.Entities.ProductCategory", "Category")
                        .WithMany("ProductCaches")
                        .HasForeignKey("CategoryId");

                    b.HasOne("PantioClassLibrary.Entities.User", "User")
                        .WithMany("ProductCaches")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PantioClassLibrary.Entities.Receipt", b =>
                {
                    b.HasOne("PantioClassLibrary.Entities.StoreConnection", "StoreConnection")
                        .WithMany("Receipts")
                        .HasForeignKey("StoreConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PantioClassLibrary.Entities.User", "User")
                        .WithMany("Receipts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoreConnection");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PantioClassLibrary.Entities.ReceiptLine", b =>
                {
                    b.HasOne("PantioClassLibrary.Entities.Receipt", "Receipt")
                        .WithMany("ReceiptLines")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("PantioClassLibrary.Entities.Recipe", b =>
                {
                    b.HasOne("PantioClassLibrary.Entities.User", "User")
                        .WithMany("Recipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PantioClassLibrary.Entities.RecipeEntry", b =>
                {
                    b.HasOne("PantioClassLibrary.Entities.InventoryItem", "InventoryItem")
                        .WithMany("RecipeEntries")
                        .HasForeignKey("InventoryItemId");

                    b.HasOne("PantioClassLibrary.Entities.Recipe", "Recipe")
                        .WithMany("Entries")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("PantioClassLibrary.Entities.ShoppingList", b =>
                {
                    b.HasOne("PantioClassLibrary.Entities.User", "User")
                        .WithMany("ShoppingLists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PantioClassLibrary.Entities.ShoppingListItem", b =>
                {
                    b.HasOne("PantioClassLibrary.Entities.ShoppingList", "ShoppingList")
                        .WithMany("Items")
                        .HasForeignKey("ShoppingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShoppingList");
                });

            modelBuilder.Entity("PantioClassLibrary.Entities.StoreConnection", b =>
                {
                    b.HasOne("PantioClassLibrary.Entities.User", "User")
                        .WithMany("StoreConnections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PantioClassLibrary.Entities.UserProfile", b =>
                {
                    b.HasOne("PantioClassLibrary.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("PantioClassLibrary.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PantioClassLibrary.Entities.ExpiryDate", b =>
                {
                    b.Navigation("ExpiryNotifications");
                });

            modelBuilder.Entity("PantioClassLibrary.Entities.Inventory", b =>
                {
                    b.Navigation("InventoryItems");
                });

            modelBuilder.Entity("PantioClassLibrary.Entities.InventoryItem", b =>
                {
                    b.Navigation("ExpiryDate");

                    b.Navigation("NutritionFacts");

                    b.Navigation("RecipeEntries");
                });

            modelBuilder.Entity("PantioClassLibrary.Entities.ProductCache", b =>
                {
                    b.Navigation("NutritionFacts");
                });

            modelBuilder.Entity("PantioClassLibrary.Entities.ProductCategory", b =>
                {
                    b.Navigation("InventoryItems");

                    b.Navigation("ProductCaches");
                });

            modelBuilder.Entity("PantioClassLibrary.Entities.Receipt", b =>
                {
                    b.Navigation("ReceiptLines");
                });

            modelBuilder.Entity("PantioClassLibrary.Entities.ReceiptLine", b =>
                {
                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("PantioClassLibrary.Entities.Recipe", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("PantioClassLibrary.Entities.ShoppingList", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("PantioClassLibrary.Entities.StoreConnection", b =>
                {
                    b.Navigation("Receipts");
                });

            modelBuilder.Entity("PantioClassLibrary.Entities.User", b =>
                {
                    b.Navigation("ExpiryNotifications");

                    b.Navigation("InventoryItems");

                    b.Navigation("ProductCaches");

                    b.Navigation("Profile");

                    b.Navigation("Receipts");

                    b.Navigation("Recipes");

                    b.Navigation("ShoppingLists");

                    b.Navigation("StoreConnections");
                });
#pragma warning restore 612, 618
        }
    }
}
