<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>244a47f7-fb02-495f-882e-695f27671eac</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>.</DockerfileContext>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\PantioClassLibrary\PantioClassLibrary.csproj" />
	  <ProjectReference Include="..\PantioRepository\PantioRepository.csproj" />
	</ItemGroup>

</Project>
